# News Management Service Configuration
# Конфигурация сервиса управления новостями

server:
  port: 8082
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: "localhost"
  port: 5433
  user: "news_pulse_user"
  password: "news_pulse_secure_password_2024"
  dbname: "news_pulse"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "1h"

api:
  # Максимальное количество новостей на страницу
  max_page_size: 100
  # Размер страницы по умолчанию
  default_page_size: 20
  # Максимальная длина поискового запроса
  max_search_length: 500
  # Таймаут для запросов к базе данных
  db_timeout: "30s"
  # Включить полнотекстовый поиск
  enable_fulltext_search: true

caching:
  # Включить кеширование
  enabled: true
  # TTL для кеша новостей (в секундах)
  news_ttl: 60  # 1 минута для более быстрого обновления
  # TTL для кеша категорий
  categories_ttl: 1800  # 30 минут
  # TTL для кеша источников
  sources_ttl: 1800  # 30 минут
  # Максимальный размер кеша (количество элементов)
  max_size: 5000

logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "/var/log/news-management-service.log"

health:
  # Порт для health check endpoint
  port: 8092
  # Путь для health check
  path: "/health"

metrics:
  # Включить метрики Prometheus
  enabled: true
  port: 9092
  path: "/metrics"

# Настройки для разных окружений
environments:
  development:
    logging:
      level: "debug"
    api:
      default_page_size: 10
    caching:
      enabled: false
  
  production:
    logging:
      level: "warn"
    api:
      max_page_size: 50
      default_page_size: 20
    caching:
      enabled: true
      news_ttl: 600  # 10 минут в production
